config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controller=>{registrations: "registrations"}
  resources :events
  resources :invitations
  resources :users

  root"events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :invitations
    has_many :attendees, through: :invitations

    scope :past, -> {where("date < ?",DateTime.now)}
    scope :future, -> {where("date >= ?",DateTime.now)}


    validates :title, presence: true
    validates :location, presence: true
    validates :date, presence: true
    validates :description, presence: true, length: {minimum: 10}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :created_events, class_name: "Event", foreign_key: "creator_id", dependent: :destroy
has_many :invitations, foreign_key: :attendee_id
has_many :attended_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except:[:show, :index]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def new
    @event = current_user.created_events.build
    
  end

  def create
    @event = current_user.created_events.build(event_params)
    @event.attendees << current_user
    
    if @event.save
      flash[:success] = 'Event created successfully'

      redirect_to @event
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = 'Event updated successfully'

      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private
  def event_params
    params.require(:event).permit(:title,:date,:location,:description)
  end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    def create
      event = Event.find(params[:event_id])
      invitation = current_user.invitations.new(event: event)
        
      if invitation.save
            flash[:notice] = "You are attending #{event.title}."
            redirect_to event
          else
            flash[:alert] = 'Could not enroll.'
            redirect_to event
          end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    def sign_up_params
        params.require(:user).permit(:username,:email, :password, :password_conformation)
    end

    def account_update_params
        params.require(:user).permit(:username,:email, :password, :password_conformation, :current_password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show]
    def index
        @users = User.all
      end
    
      def show
        @user = User.find(params[:id])
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_with model:@event do |f| %>
<div>
    <%= f.label "Title" %><br><br>
    <%= f.text_field :title, placeholder: "Title"%>
    
</div>
<br><br>

<div>
    <%= f.label "Date" %><br><br>
    <%= f.date_select :date %>
</div>
<br><br>

<div>
    <%= f.label "Location" %><br><br>
    <%= f.text_field :location, placeholder: "Location"%>
    >
</div>
<br><br>

<div>
    <%= f.label "Descripion" %><br><br>
    <%= f.text_area :description, placeholder: "Descripion"%>
    
</div>
<br><br>

<div>
    <%= f.submit "Submit" %>
</div>   
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>
<strong><%= link_to "New Event", new_event_path%></strong>
<br><br>
<h2>Upcoming events: <h2>
<ul>
  <% @events.future.each do |event| %>
    <li>
      <%= link_to event.title, event %>
    </li>
  <% end %>
</ul>
<br><br>
<h2>Past events: <h2>
<ul>
  <% @events.past.each do |event| %>
    <li>
      <%= link_to event.title, event %>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model:@event do |f| %>
<div>
    <%= f.label "Title" %><br><br>
    <%= f.text_field :title, placeholder: "Title"%>
    
</div>
<br><br>

<div>
    <%= f.label "Date" %><br><br>
    <%= f.date_select :date %>
</div>
<br><br>

<div>
    <%= f.label "Location" %><br><br>
    <%= f.text_field :location, placeholder: "Location"%>
    >
</div>
<br><br>

<div>
    <%= f.label "Descripion" %><br><br>
    <%= f.text_area :description, placeholder: "Descripion"%>
    
</div>
<br><br>

<div>
    <%= f.submit "Submit" %>
</div>   
<% end %>

app/views/events/show.html.erb
<h1> <%= @event.title %> </h1><br><br>
    <p>Written by User <%= @event.creator.username%></p><br>

    <p>Date: <%= @event.date%></p><br>
    <p>Location: <%= @event.location%></p><br>
    <p>Description: <%= @event.description%><br><br>
    

    <p>Attendees: </p>
    <% if @event.attendees.any? %>
    <% @event.attendees.each do |attendee| %>
    <ul>
    <%= link_to attendee.username,user_path(attendee) %>
    </ul>
    <% end %>
    <% else %>
    <p>nobody yet</p>
    <% end %>

    <%= button_to "Join", invitations_path(event_id: @event.id, attendee_id: current_user.id) %>
    <br><br>
    <% if current_user == @event.creator %>
    <%= link_to 'Edit', edit_event_path(@event) %>
    <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <br><br>
    <%= link_to "Events", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.username %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Hosted event's: </h2>

<div>
<% @user.created_events.each do |event| %>
    <%= event.date %> - <%= link_to event.title, event%>
    <br><br>
<% end %>
</div>

<% if @user.attended_events %>
  <h3>Registered Events: </h3>
  <% @user.attended_events.future.each do |event| %>
    <%= link_to event.title,event_path(event) %><br />
  <% end %>
<% else %>
  <h3>No events registered.</h3>
<% end %>

<% if @user.attended_events %>
  <h3>Past Events: </h3>
  <% @user.attended_events.past.each do |event| %>
    <%= link_to event.title,event_path(event) %><br />
  <% end %>
<% else %>
  <h3>No events attended.</h3>
<% end %>